"use strict";(()=>{(function(){"use strict";let a=window.vscodeApi;if(!a){console.error("VS Code API not found. Make sure editor.ts loads first.");return}function g(e,t=50){let i=0,n=setInterval(()=>{i++,window.editorAPI?(clearInterval(n),console.log("Editor API ready, initializing toolbar"),e()):i>=t&&(clearInterval(n),console.error("Editor API not available after waiting"))},100)}let l={"heading-toggle":()=>{let e=document.getElementById("heading-menu");if(console.log("Heading toggle clicked, menu:",e),e){let t=e.classList.contains("show");e.classList.toggle("show"),console.log("Menu toggled, now showing:",!t)}else console.error("Heading menu not found in DOM")},heading1:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`# ${t.text}`):e.insertAtCursor("# "),r()},heading2:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`## ${t.text}`):e.insertAtCursor("## "),r()},heading3:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`### ${t.text}`):e.insertAtCursor("### "),r()},heading4:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`#### ${t.text}`):e.insertAtCursor("#### "),r()},heading5:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`##### ${t.text}`):e.insertAtCursor("##### "),r()},heading6:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`###### ${t.text}`):e.insertAtCursor("###### "),r()},bold:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`**${t.text}**`):e.insertTemplate("**","**","bold text")},italic:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`*${t.text}*`):e.insertTemplate("*","*","italic text")},link:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.insertTemplate(`[${t.text}](`,")","url"):e.insertTemplate("[","](url)","link text")},image:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.insertTemplate(`![${t.text}](`,")","image-url"):e.insertTemplate("![","](image-url)","alt text")},code:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`\`\`\`
${t.text}
\`\`\``):e.insertTemplate("```\n","\n```","code")},"inline-code":()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`\`${t.text}\``):e.insertTemplate("`","`","code")},strikethrough:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`~~${t.text}~~`):e.insertTemplate("~~","~~","strikethrough text")},highlight:()=>{let e=window.editorAPI,t=e.getSelection();t.text?e.replaceSelection(`==${t.text}==`):e.insertTemplate("==","==","highlight text")},quote:()=>{let e=window.editorAPI,t=e.getSelection();if(t.text){let n=t.text.split(`
`).map(o=>`> ${o}`).join(`
`);e.replaceSelection(n)}else e.insertAtCursor("> ")},table:()=>{window.editorAPI.insertAtCursor(`| Header 1 | Header 2 | Header 3 |
| -------- | -------- | -------- |
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |
`)},"unordered-list":()=>{let e=window.editorAPI,t=e.getSelection();if(t.text){let n=t.text.split(`
`).map(o=>o.trim()?`- ${o}`:"").join(`
`);e.replaceSelection(n)}else e.insertAtCursor("- ")},"ordered-list":()=>{let e=window.editorAPI,t=e.getSelection();if(t.text){let n=t.text.split(`
`).map((o,c)=>o.trim()?`${c+1}. ${o}`:"").join(`
`);e.replaceSelection(n)}else e.insertAtCursor("1. ")},"task-list":()=>{let e=window.editorAPI,t=e.getSelection();if(t.text){let n=t.text.split(`
`).map(o=>o.trim()?`- [ ] ${o}`:"").join(`
`);e.replaceSelection(n)}else e.insertAtCursor("- [ ] ")},"emoji-toggle":()=>{let e=document.getElementById("emoji-menu");e&&e.classList.toggle("show")},"insert-emoji":e=>{let t=window.editorAPI,n=e?.target?.getAttribute("data-emoji");n&&t.insertAtCursor(n);let o=document.getElementById("emoji-menu");o&&o.classList.remove("show")},"export-pdf":()=>{a.postMessage({type:"command",command:"md-editor-pro.exportPdfFile"})},translate:()=>{a.postMessage({type:"command",command:"md-editor-pro.translate"})}};function r(){let e=document.getElementById("heading-menu");e&&e.classList.remove("show")}function A(){console.log("Initializing toolbar...");let e=document.getElementById("heading-menu");console.log("Heading menu found:",!!e),e&&console.log("Heading menu children:",e.children.length),document.addEventListener("click",t=>{let i=t.target,n=i.closest("[data-action]");if(n){let o=n.getAttribute("data-action");console.log(`Button clicked with action: ${o}`);let c=n.classList.contains("toolbar-dropdown-item");if(o&&l[o]){t.preventDefault(),t.stopPropagation();try{if(console.log(`Executing action: ${o}`),o==="insert-emoji"?l[o](t):l[o](),!o.includes("toggle")&&!o.includes("export")&&!o.includes("translate")){let s=window.editorAPI;s&&s.focus&&setTimeout(()=>s.focus(),10)}}catch(s){console.error(`Error executing action ${o}:`,s)}}else o&&console.warn(`Unknown action: ${o}`)}else{let o=i.closest(".toolbar-dropdown"),c=i.closest(".toolbar-dropdown-menu");if(!o&&!c){r();let s=document.getElementById("emoji-menu");s&&s.classList.remove("show")}}}),console.log("Toolbar initialized successfully")}window.toolbarActions=l;function d(){g(A)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",d):d()})();})();
